# Generated by Django 4.1.2 on 2022-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('RequestId', models.AutoField(primary_key=True, serialize=False)),
                ('AddressFrom', models.CharField(max_length=500)),
                ('AddressTo', models.CharField(max_length=500)),
                ('ClientID', models.CharField(max_length=500)),
                ('ReceiverID', models.CharField(max_length=500)),
                ('ExecutiveID', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=50)),
                ('AssetSensitivity', models.CharField(max_length=50)),
                ('AssetType', models.CharField(max_length=50)),
            ],
        ),
    ]
